name: Build and test application
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check docker
        run: docker

      - name: Check docker compose
        run: docker-compose

      - uses: actions/checkout@v3

      # - name: Build image
      #   run: docker build -t seunghwan/web -f Dockerfile.dev .
      #   working-directory: frontend

      # - name: Run test
      #   run: docker run seunghwan/web npm run test -- --coverage

      # - name: Install AWS CLI
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install
      #     aws --version

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #     aws-region: ap-northeast-2
