name: Build and test application
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker

    steps:
      - uses: actions/checkout@v3

      - name: Check docker
        run: docker
