name: Build and test application
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build -t seunghwan/web -f frontend/Dockerfile.dev .

      - name: Run test
        run: docker run seunghwan/web npm run test -- --coverage
